project_id = "exunjybsermnxvrvyxnj"

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.run-fixed-expenses]
verify_jwt = true

[functions.run-recurring-payrolls]
verify_jwt = true

[functions.reject-order-modification]
verify_jwt = true

[functions.update-collections-cache]
verify_jwt = false

[functions.check-fiscal-withdrawals]
verify_jwt = false

[functions.check-overdue-loans]
verify_jwt = false

[functions.check-unpaid-payrolls]
verify_jwt = false

[functions.check-pending-collections]
verify_jwt = false

[functions.calculate-vat-status]
verify_jwt = false

[functions.process-scheduled-services]
verify_jwt = false

[functions.generate-policy-payments]
verify_jwt = false

[functions.process-access-orders]
verify_jwt = false

[functions.create-development-order]
verify_jwt = false
